// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8LlCUYQmJfoAkyG80n0o8cCi6bqVuYt0',
    appId: '1:86873906490:android:faa0b939de1f96bf6ec403',
    messagingSenderId: '86873906490',
    projectId: 'chasse-infos',
    databaseURL: 'https://chasse-infos-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chasse-infos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb7_TiQZbW6PaPq9AXdjMws6QVpC0tPPI',
    appId: '1:86873906490:ios:8ced5cc1934c14806ec403',
    messagingSenderId: '86873906490',
    projectId: 'chasse-infos',
    databaseURL: 'https://chasse-infos-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chasse-infos.appspot.com',
    androidClientId: '86873906490-595cokblsotig7p59ka307stdks8ngnf.apps.googleusercontent.com',
    iosClientId: '86873906490-qg8645f3n8t6a3trjpadmto5bbfdc3el.apps.googleusercontent.com',
    iosBundleId: 'com.example.chasseInfos',
  );
}
